version: '3.8'
services:
  todo-application:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-application-image:latest
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      todo-network:
        ipv4_address: 172.25.0.10
    secrets:
      - mysql_root_password
    entrypoint: ["/bin/sh", "-c", "export SPRING_DATASOURCE_PASSWORD=$(cat /run/secrets/mysql_root_password) && exec java -jar app.jar"]

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: tododb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      todo-network:
        ipv4_address: 172.25.0.20
    secrets:
      - mysql_root_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$(cat /run/secrets/mysql_root_password)"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
    driver: local

networks:
  todo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
